stages:
  - deploy

deploy:
#   image:
#     name: lachlanevenson/k8s-kubectl:latest
#     entrypoint: [""]
  stage: deploy
  script:
    - env
    - kubectl version
    - kubectl apply -k ./app/base/